spring:
  application:
    name: Lavu-Lavu
  datasource:
    url: jdbc:mysql://database-lavu.cxaau2eum1u1.ap-northeast-2.rds.amazonaws.com:3306/LavuLavu?useSSL=false&serverTimezone=Asia/Seoul
    username: chanwoo
    password: 4613112
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # ??? ?? ???? (?? ????? update, ?? ????? none ??)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  redis:
#    host: localhost # Redis ???
#    port: 6379 # Redis ??
#    timeout: 60000 # ?? ?? ?? (???)

logging:
  level:
    org:
      springframework: DEBUG # ?? ?? ?? (??? DEBUG ?? ??)

server:
  port: 8080
  ssl:
    key-store: file:/app/resources/keystore.p12
    key-store-password: 4613112
    key-store-type: PKCS12
    key-alias: lavu-key